openapi: 3.0.1
info:
  contact:
    email: rpshkarki@gmail.com
    name: Rupesh
  description: OpenApi documentation for Spring security
  license:
    name: Lisc Name
    url: https://www.rpsh.com
  termsOfService: Terms of Service
  title: OpenApi Specification - XXMORTIS
  version: "1.0"
servers:
- description: Local ENV
  url: http://localhost:8088/api/v1
- description: PROD ENV
  url: https://rpshkarki.com/courses
security:
- bearerAuth: []
paths:
  /feedbacks:
    post:
      operationId: saveFeedback
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      tags:
      - Feedback
      x-content-type: application/json
      x-accepts: application/json
  /books:
    get:
      operationId: findAllBooks
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponseBookResponse'
          description: OK
      tags:
      - Book
      x-accepts: application/json
    post:
      operationId: saveBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      tags:
      - Book
      x-content-type: application/json
      x-accepts: application/json
  /books/cover/{book-id}:
    post:
      operationId: uploadBookCoverPicture
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      requestBody:
        content:
          multipart/from-data:
            schema:
              $ref: '#/components/schemas/uploadBookCoverPicture_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: OK
      tags:
      - Book
      x-content-type: multipart/from-data
      x-accepts: application/json
  /books/borrow/{book-id}:
    post:
      operationId: borrowBook
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /auth/register:
    post:
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                type: object
          description: Accepted
      tags:
      - authentication
      x-content-type: application/json
      x-accepts: application/json
  /auth/authenticate:
    post:
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
          description: OK
      tags:
      - authentication
      x-content-type: application/json
      x-accepts: application/json
  /books/shareable/{book-id}:
    patch:
      operationId: updateSharableStatus
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /books/borrow/return/{book-id}:
    patch:
      operationId: returnBorrowBook
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /books/borrow/return/approved/{book-id}:
    patch:
      operationId: approvedReturnBorrowBook
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /books/archived/{book-id}:
    patch:
      operationId: updateArchivedStatus
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /feedbacks/book/{book-id}:
    get:
      operationId: findAllFeedbackByBook
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponseFeedbackResponse'
          description: OK
      tags:
      - Feedback
      x-accepts: application/json
  /books/{book-id}:
    get:
      operationId: findBookById
      parameters:
      - explode: false
        in: path
        name: book-id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponse'
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /books/returned:
    get:
      operationId: findALlReturnedBooks
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponseBorrowedBooksResponse'
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /books/owner:
    get:
      operationId: findALlBooksByOwner
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponseBookResponse'
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /books/borrowed:
    get:
      operationId: findALlBorrowedBooks
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponseBorrowedBooksResponse'
          description: OK
      tags:
      - Book
      x-accepts: application/json
  /auth/activate-account:
    get:
      operationId: confirm
      parameters:
      - explode: true
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          description: OK
      tags:
      - authentication
      x-accepts: application/json
components:
  schemas:
    FeedbackRequest:
      example:
        note: 0.8008281904610115
        comment: comment
        bookId: 6
      properties:
        note:
          format: double
          type: number
        comment:
          type: string
        bookId:
          format: int32
          type: integer
      required:
      - bookId
      - comment
      type: object
    BookRequest:
      example:
        shareable: true
        authorName: authorName
        isbn: isbn
        id: 0
        synopsis: synopsis
        title: title
      properties:
        id:
          format: int32
          type: integer
        title:
          type: string
        authorName:
          type: string
        isbn:
          type: string
        synopsis:
          type: string
        shareable:
          type: boolean
      required:
      - authorName
      - isbn
      - shareable
      - synopsis
      - title
      type: object
    RegistrationRequest:
      example:
        firstname: firstname
        password: password
        email: email
        lastname: lastname
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        password:
          maxLength: 2147483647
          minLength: 8
          type: string
      required:
      - email
      - firstname
      - lastname
      - password
      type: object
    AuthenticationRequest:
      example:
        password: password
        email: email
      properties:
        email:
          type: string
        password:
          maxLength: 2147483647
          minLength: 8
          type: string
      required:
      - email
      - password
      type: object
    AuthenticationResponse:
      example:
        token: token
      properties:
        token:
          type: string
      type: object
    FeedbackResponse:
      example:
        note: 0.8008281904610115
        comment: comment
        ownFeedback: true
      properties:
        note:
          format: double
          type: number
        comment:
          type: string
        ownFeedback:
          type: boolean
      type: object
    PageResponseFeedbackResponse:
      example:
        number: 6
        size: 1
        last: true
        totalPages: 5
        content:
        - note: 0.8008281904610115
          comment: comment
          ownFeedback: true
        - note: 0.8008281904610115
          comment: comment
          ownFeedback: true
        first: true
        totalElements: 5
      properties:
        content:
          items:
            $ref: '#/components/schemas/FeedbackResponse'
          type: array
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalElements:
          format: int64
          type: integer
        totalPages:
          format: int32
          type: integer
        first:
          type: boolean
        last:
          type: boolean
      type: object
    Book:
      example:
        shareable: true
        owner: null
        lastModifiedDate: 2000-01-23
        lastModifiedBy: 2
        isbn: isbn
        feedbacks:
        - note: 2.027123023002322
          createdDate: 2000-01-23
          lastModifiedDate: 2000-01-23
          createdBy: 9
          lastModifiedBy: 3
          book: null
          comment: comment
          id: 7
        - note: 2.027123023002322
          createdDate: 2000-01-23
          lastModifiedDate: 2000-01-23
          createdBy: 9
          lastModifiedBy: 3
          book: null
          comment: comment
          id: 7
        histories:
        - returnApproved: true
          createdDate: 2000-01-23
          lastModifiedDate: 2000-01-23
          createdBy: 7
          lastModifiedBy: 1
          book: null
          id: 4
          returned: true
          user: null
        - returnApproved: true
          createdDate: 2000-01-23
          lastModifiedDate: 2000-01-23
          createdBy: 7
          lastModifiedBy: 1
          book: null
          id: 4
          returned: true
          user: null
        synopsis: synopsis
        title: title
        bookCover: bookCover
        archived: true
        createdDate: 2000-01-23
        createdBy: 5
        rate: 1.0246457001441578
        authorName: authorName
        id: 5
      properties:
        id:
          format: int32
          type: integer
        createdDate:
          format: date
          type: string
        lastModifiedDate:
          format: date
          type: string
        createdBy:
          format: int32
          type: integer
        lastModifiedBy:
          format: int32
          type: integer
        title:
          type: string
        authorName:
          type: string
        isbn:
          type: string
        synopsis:
          type: string
        bookCover:
          type: string
        archived:
          type: boolean
        shareable:
          type: boolean
        owner:
          $ref: '#/components/schemas/User'
        feedbacks:
          items:
            $ref: '#/components/schemas/Feedback'
          type: array
          uniqueItems: true
        histories:
          items:
            $ref: '#/components/schemas/BookTransactionHistory'
          type: array
        rate:
          format: double
          type: number
      type: object
    BookResponse:
      example:
        owner:
          accountLocked: true
          firstname: firstname
          lastModifiedDate: 2000-01-23T04:56:07.000+00:00
          roles:
          - createdDate: 2000-01-23T04:56:07.000+00:00
            lastModifiedDate: 2000-01-23T04:56:07.000+00:00
            name: name
            id: 1
          - createdDate: 2000-01-23T04:56:07.000+00:00
            lastModifiedDate: 2000-01-23T04:56:07.000+00:00
            name: name
            id: 1
          credentialsNonExpired: true
          fullName: fullName
          dateOfBirth: 2000-01-23
          histories:
          - returnApproved: true
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 7
            lastModifiedBy: 1
            book: null
            id: 4
            returned: true
            user: null
          - returnApproved: true
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 7
            lastModifiedBy: 1
            book: null
            id: 4
            returned: true
            user: null
          enabled: true
          authorities:
          - authority: authority
          - authority: authority
          lastname: lastname
          password: password
          books:
          - shareable: true
            owner: null
            lastModifiedDate: 2000-01-23
            lastModifiedBy: 2
            isbn: isbn
            feedbacks:
            - note: 2.027123023002322
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 9
              lastModifiedBy: 3
              book: null
              comment: comment
              id: 7
            - note: 2.027123023002322
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 9
              lastModifiedBy: 3
              book: null
              comment: comment
              id: 7
            histories:
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            synopsis: synopsis
            title: title
            bookCover: bookCover
            archived: true
            createdDate: 2000-01-23
            createdBy: 5
            rate: 1.0246457001441578
            authorName: authorName
            id: 5
          - shareable: true
            owner: null
            lastModifiedDate: 2000-01-23
            lastModifiedBy: 2
            isbn: isbn
            feedbacks:
            - note: 2.027123023002322
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 9
              lastModifiedBy: 3
              book: null
              comment: comment
              id: 7
            - note: 2.027123023002322
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 9
              lastModifiedBy: 3
              book: null
              comment: comment
              id: 7
            histories:
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            synopsis: synopsis
            title: title
            bookCover: bookCover
            archived: true
            createdDate: 2000-01-23
            createdBy: 5
            rate: 1.0246457001441578
            authorName: authorName
            id: 5
          createdDate: 2000-01-23T04:56:07.000+00:00
          name: name
          accountNonExpired: true
          id: 6
          email: email
          accountNonLocked: true
          username: username
        cover:
        - cover
        - cover
        shareable: true
        archived: true
        rate: 1.4894159098541704
        authorName: authorName
        isbn: isbn
        id: 0
        synopsis: synopsis
        title: title
      properties:
        id:
          format: int32
          type: integer
        title:
          type: string
        authorName:
          type: string
        isbn:
          type: string
        synopsis:
          type: string
        owner:
          $ref: '#/components/schemas/User'
        cover:
          items:
            format: byte
            type: string
          type: array
        rate:
          format: double
          type: number
        archived:
          type: boolean
        shareable:
          type: boolean
      type: object
    BookTransactionHistory:
      example:
        returnApproved: true
        createdDate: 2000-01-23
        lastModifiedDate: 2000-01-23
        createdBy: 7
        lastModifiedBy: 1
        book: null
        id: 4
        returned: true
        user: null
      properties:
        id:
          format: int32
          type: integer
        createdDate:
          format: date
          type: string
        lastModifiedDate:
          format: date
          type: string
        createdBy:
          format: int32
          type: integer
        lastModifiedBy:
          format: int32
          type: integer
        returned:
          type: boolean
        returnApproved:
          type: boolean
        user:
          $ref: '#/components/schemas/User'
        book:
          $ref: '#/components/schemas/Book'
      type: object
    Feedback:
      example:
        note: 2.027123023002322
        createdDate: 2000-01-23
        lastModifiedDate: 2000-01-23
        createdBy: 9
        lastModifiedBy: 3
        book: null
        comment: comment
        id: 7
      properties:
        id:
          format: int32
          type: integer
        createdDate:
          format: date
          type: string
        lastModifiedDate:
          format: date
          type: string
        createdBy:
          format: int32
          type: integer
        lastModifiedBy:
          format: int32
          type: integer
        note:
          format: double
          type: number
        comment:
          type: string
        book:
          $ref: '#/components/schemas/Book'
      type: object
    GrantedAuthority:
      example:
        authority: authority
      properties:
        authority:
          type: string
      type: object
    PageResponseBookResponse:
      example:
        number: 6
        size: 7
        last: true
        totalPages: 4
        content:
        - owner:
            accountLocked: true
            firstname: firstname
            lastModifiedDate: 2000-01-23T04:56:07.000+00:00
            roles:
            - createdDate: 2000-01-23T04:56:07.000+00:00
              lastModifiedDate: 2000-01-23T04:56:07.000+00:00
              name: name
              id: 1
            - createdDate: 2000-01-23T04:56:07.000+00:00
              lastModifiedDate: 2000-01-23T04:56:07.000+00:00
              name: name
              id: 1
            credentialsNonExpired: true
            fullName: fullName
            dateOfBirth: 2000-01-23
            histories:
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            enabled: true
            authorities:
            - authority: authority
            - authority: authority
            lastname: lastname
            password: password
            books:
            - shareable: true
              owner: null
              lastModifiedDate: 2000-01-23
              lastModifiedBy: 2
              isbn: isbn
              feedbacks:
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              histories:
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              synopsis: synopsis
              title: title
              bookCover: bookCover
              archived: true
              createdDate: 2000-01-23
              createdBy: 5
              rate: 1.0246457001441578
              authorName: authorName
              id: 5
            - shareable: true
              owner: null
              lastModifiedDate: 2000-01-23
              lastModifiedBy: 2
              isbn: isbn
              feedbacks:
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              histories:
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              synopsis: synopsis
              title: title
              bookCover: bookCover
              archived: true
              createdDate: 2000-01-23
              createdBy: 5
              rate: 1.0246457001441578
              authorName: authorName
              id: 5
            createdDate: 2000-01-23T04:56:07.000+00:00
            name: name
            accountNonExpired: true
            id: 6
            email: email
            accountNonLocked: true
            username: username
          cover:
          - cover
          - cover
          shareable: true
          archived: true
          rate: 1.4894159098541704
          authorName: authorName
          isbn: isbn
          id: 0
          synopsis: synopsis
          title: title
        - owner:
            accountLocked: true
            firstname: firstname
            lastModifiedDate: 2000-01-23T04:56:07.000+00:00
            roles:
            - createdDate: 2000-01-23T04:56:07.000+00:00
              lastModifiedDate: 2000-01-23T04:56:07.000+00:00
              name: name
              id: 1
            - createdDate: 2000-01-23T04:56:07.000+00:00
              lastModifiedDate: 2000-01-23T04:56:07.000+00:00
              name: name
              id: 1
            credentialsNonExpired: true
            fullName: fullName
            dateOfBirth: 2000-01-23
            histories:
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            - returnApproved: true
              createdDate: 2000-01-23
              lastModifiedDate: 2000-01-23
              createdBy: 7
              lastModifiedBy: 1
              book: null
              id: 4
              returned: true
              user: null
            enabled: true
            authorities:
            - authority: authority
            - authority: authority
            lastname: lastname
            password: password
            books:
            - shareable: true
              owner: null
              lastModifiedDate: 2000-01-23
              lastModifiedBy: 2
              isbn: isbn
              feedbacks:
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              histories:
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              synopsis: synopsis
              title: title
              bookCover: bookCover
              archived: true
              createdDate: 2000-01-23
              createdBy: 5
              rate: 1.0246457001441578
              authorName: authorName
              id: 5
            - shareable: true
              owner: null
              lastModifiedDate: 2000-01-23
              lastModifiedBy: 2
              isbn: isbn
              feedbacks:
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              - note: 2.027123023002322
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 9
                lastModifiedBy: 3
                book: null
                comment: comment
                id: 7
              histories:
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              - returnApproved: true
                createdDate: 2000-01-23
                lastModifiedDate: 2000-01-23
                createdBy: 7
                lastModifiedBy: 1
                book: null
                id: 4
                returned: true
                user: null
              synopsis: synopsis
              title: title
              bookCover: bookCover
              archived: true
              createdDate: 2000-01-23
              createdBy: 5
              rate: 1.0246457001441578
              authorName: authorName
              id: 5
            createdDate: 2000-01-23T04:56:07.000+00:00
            name: name
            accountNonExpired: true
            id: 6
            email: email
            accountNonLocked: true
            username: username
          cover:
          - cover
          - cover
          shareable: true
          archived: true
          rate: 1.4894159098541704
          authorName: authorName
          isbn: isbn
          id: 0
          synopsis: synopsis
          title: title
        first: true
        totalElements: 1
      properties:
        content:
          items:
            $ref: '#/components/schemas/BookResponse'
          type: array
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalElements:
          format: int64
          type: integer
        totalPages:
          format: int32
          type: integer
        first:
          type: boolean
        last:
          type: boolean
      type: object
    Role:
      example:
        createdDate: 2000-01-23T04:56:07.000+00:00
        lastModifiedDate: 2000-01-23T04:56:07.000+00:00
        name: name
        id: 1
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        createdDate:
          format: date-time
          type: string
        lastModifiedDate:
          format: date-time
          type: string
      type: object
    User:
      example:
        accountLocked: true
        firstname: firstname
        lastModifiedDate: 2000-01-23T04:56:07.000+00:00
        roles:
        - createdDate: 2000-01-23T04:56:07.000+00:00
          lastModifiedDate: 2000-01-23T04:56:07.000+00:00
          name: name
          id: 1
        - createdDate: 2000-01-23T04:56:07.000+00:00
          lastModifiedDate: 2000-01-23T04:56:07.000+00:00
          name: name
          id: 1
        credentialsNonExpired: true
        fullName: fullName
        dateOfBirth: 2000-01-23
        histories:
        - returnApproved: true
          createdDate: 2000-01-23
          lastModifiedDate: 2000-01-23
          createdBy: 7
          lastModifiedBy: 1
          book: null
          id: 4
          returned: true
          user: null
        - returnApproved: true
          createdDate: 2000-01-23
          lastModifiedDate: 2000-01-23
          createdBy: 7
          lastModifiedBy: 1
          book: null
          id: 4
          returned: true
          user: null
        enabled: true
        authorities:
        - authority: authority
        - authority: authority
        lastname: lastname
        password: password
        books:
        - shareable: true
          owner: null
          lastModifiedDate: 2000-01-23
          lastModifiedBy: 2
          isbn: isbn
          feedbacks:
          - note: 2.027123023002322
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 9
            lastModifiedBy: 3
            book: null
            comment: comment
            id: 7
          - note: 2.027123023002322
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 9
            lastModifiedBy: 3
            book: null
            comment: comment
            id: 7
          histories:
          - returnApproved: true
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 7
            lastModifiedBy: 1
            book: null
            id: 4
            returned: true
            user: null
          - returnApproved: true
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 7
            lastModifiedBy: 1
            book: null
            id: 4
            returned: true
            user: null
          synopsis: synopsis
          title: title
          bookCover: bookCover
          archived: true
          createdDate: 2000-01-23
          createdBy: 5
          rate: 1.0246457001441578
          authorName: authorName
          id: 5
        - shareable: true
          owner: null
          lastModifiedDate: 2000-01-23
          lastModifiedBy: 2
          isbn: isbn
          feedbacks:
          - note: 2.027123023002322
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 9
            lastModifiedBy: 3
            book: null
            comment: comment
            id: 7
          - note: 2.027123023002322
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 9
            lastModifiedBy: 3
            book: null
            comment: comment
            id: 7
          histories:
          - returnApproved: true
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 7
            lastModifiedBy: 1
            book: null
            id: 4
            returned: true
            user: null
          - returnApproved: true
            createdDate: 2000-01-23
            lastModifiedDate: 2000-01-23
            createdBy: 7
            lastModifiedBy: 1
            book: null
            id: 4
            returned: true
            user: null
          synopsis: synopsis
          title: title
          bookCover: bookCover
          archived: true
          createdDate: 2000-01-23
          createdBy: 5
          rate: 1.0246457001441578
          authorName: authorName
          id: 5
        createdDate: 2000-01-23T04:56:07.000+00:00
        name: name
        accountNonExpired: true
        id: 6
        email: email
        accountNonLocked: true
        username: username
      properties:
        id:
          format: int32
          type: integer
        firstname:
          type: string
        lastname:
          type: string
        dateOfBirth:
          format: date
          type: string
        email:
          type: string
        password:
          type: string
        accountLocked:
          type: boolean
        enabled:
          type: boolean
        roles:
          items:
            $ref: '#/components/schemas/Role'
          type: array
        books:
          items:
            $ref: '#/components/schemas/Book'
          type: array
        createdDate:
          format: date-time
          type: string
        lastModifiedDate:
          format: date-time
          type: string
        histories:
          items:
            $ref: '#/components/schemas/BookTransactionHistory'
          type: array
        name:
          type: string
        fullName:
          type: string
        authorities:
          items:
            $ref: '#/components/schemas/GrantedAuthority'
          type: array
        accountNonExpired:
          type: boolean
        credentialsNonExpired:
          type: boolean
        accountNonLocked:
          type: boolean
        username:
          type: string
      type: object
    BorrowedBooksResponse:
      example:
        returnApproved: true
        rate: 6.027456183070403
        authorName: authorName
        isbn: isbn
        id: 0
        title: title
        returned: true
      properties:
        id:
          format: int32
          type: integer
        title:
          type: string
        authorName:
          type: string
        isbn:
          type: string
        rate:
          format: double
          type: number
        returned:
          type: boolean
        returnApproved:
          type: boolean
      type: object
    PageResponseBorrowedBooksResponse:
      example:
        number: 1
        size: 5
        last: true
        totalPages: 2
        content:
        - returnApproved: true
          rate: 6.027456183070403
          authorName: authorName
          isbn: isbn
          id: 0
          title: title
          returned: true
        - returnApproved: true
          rate: 6.027456183070403
          authorName: authorName
          isbn: isbn
          id: 0
          title: title
          returned: true
        first: true
        totalElements: 5
      properties:
        content:
          items:
            $ref: '#/components/schemas/BorrowedBooksResponse'
          type: array
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalElements:
          format: int64
          type: integer
        totalPages:
          format: int32
          type: integer
        first:
          type: boolean
        last:
          type: boolean
      type: object
    uploadBookCoverPicture_request:
      properties:
        file:
          format: binary
          type: string
      required:
      - file
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: JWT auth description
      in: header
      scheme: bearer
      type: http

